program:
	gcc -I "./include" -c ./src/Luhn_Algorithm.c -o ./lib/Luhn_Algorithm.o
	gcc -I "./include" -c ./src/Kaynak.c -o ./lib/Kaynak.o
	gcc ./lib/Luhn_Algorithm.o ./lib/Kaynak.o -o ./bin/program
	./bin/program